name: Protocol Automation

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10" # Adjust if you need a different version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run main file
      run: |
        python3 src/main.py

    - name: Run unit tests
      run: |
        python3 -m unittest test/test_bob2_protocol.py
